version: '3.8'
services:
  npb-app-dev:
    image: npb-app-dev
    container_name: npb-app-dev
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - npb-app-dev-node_modules:/app/node_modules
      - npb-app-dev-next:/app/.next
    env_file:
      - .env
    depends_on:
      - npb-db-dev

  npb-db-dev:
    image: postgres:14.3-bullseye
    container_name: npb-db-dev
    restart: unless-stopped
    ports:
      - '5555:5432'
    user: '${MY_UID}:${MY_GID}'
    volumes:
      - ./prisma/pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat-app
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  npb-app-dev-node_modules:
  npb-app-dev-next:
